//! Background connection-history recorder: polls sing-box's Clash API
//! (`crate::clash_api::get_connections`) on an interval, diffs consecutive
//! snapshots keyed by `ConnectionInfo.id`, and appends any connection that
//! disappeared between polls (i.e. finished) to a local JSON-lines file --
//! one [`HistoryEntry`] per line, most-recent-append-last.
//!
//! Opt-in only (`UserConfig::connection_history_enabled`, default `false`)
//! and wired up by `CoreManager::start`/`stop_running` -- see those for the
//! lifecycle (spawned after a successful start when enabled + a path is
//! configured, `.abort()`-ed on stop). This module itself has no opinion on
//! *whether* to run, only on the polling/diffing/persisting mechanics once
//! asked to.
//!
//! **No new time-crate dependency.** `ConnectionInfo::start` is already an
//! opaque RFC3339 string sing-box hands us verbatim (see its doc comment);
//! `end` needs the same shape but generated by this app, so `now_rfc3339`
//! hand-rolls a UTC-only RFC3339 formatter (via the well-known Howard
//! Hinnant `civil_from_days` civil-calendar algorithm) rather than pulling in
//! `chrono`/`time` for one timestamp.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use shared_types::{ConnectionsSnapshot, HistoryEntry};
use tokio::task::JoinHandle;

/// Maximum number of JSON lines kept in the history file. Enforced on every
/// write (see `append_entries`) rather than periodically -- this file will
/// never hold more than ~1000 small JSON records, so a full read+rewrite on
/// every write that would exceed the cap is cheap and simple, not a
/// performance concern worth a more clever incremental approach.
pub const MAX_HISTORY_LINES: usize = 1000;

/// Interval `CoreManager::start` spawns `HistoryRecorder` at in production.
/// Not baked directly into `HistoryRecorder::spawn` -- `spawn` takes the
/// interval as a parameter (see `spawn_with_interval`) so the real-sing-box
/// integration test below can use a much shorter one instead of waiting
/// around for real 5-second ticks.
pub const DEFAULT_POLL_INTERVAL: Duration = Duration::from_secs(5);

/// Diffs `previous` against `current`, keyed by `ConnectionInfo.id`: any
/// connection present in `previous` but absent from `current` is "finished"
/// and gets turned into a `HistoryEntry` with `end` set to `end_timestamp`
/// (the same timestamp for every entry in one diff -- they're all "noticed
/// gone" at the same poll, even if they actually closed at slightly
/// different real times between polls; sing-box gives us no closed-at
/// timestamp to be more precise than that). A connection that's still
/// present in `current` is left alone -- it hasn't finished yet.
pub fn diff_finished(
    previous: &ConnectionsSnapshot,
    current: &ConnectionsSnapshot,
    end_timestamp: &str,
) -> Vec<HistoryEntry> {
    let current_ids: HashSet<&str> = current.connections.iter().map(|c| c.id.as_str()).collect();

    previous
        .connections
        .iter()
        .filter(|c| !current_ids.contains(c.id.as_str()))
        .map(|c| HistoryEntry {
            id: c.id.clone(),
            metadata: c.metadata.clone(),
            upload: c.upload,
            download: c.download,
            start: c.start.clone(),
            end: end_timestamp.to_string(),
            chains: c.chains.clone(),
            rule: c.rule.clone(),
        })
        .collect()
}

/// Appends `entries` (each serialized as one JSON line) to `path`, creating
/// the file and its parent directory if missing, then truncates to the most
/// recent `MAX_HISTORY_LINES` lines if the append pushed it over that cap.
/// A no-op if `entries` is empty (no file created just from an empty diff).
///
/// Implementation is "read everything, mutate in memory, rewrite everything"
/// rather than true append-mode + occasional separate truncation -- simple
/// and correct, and cheap enough at this file's capped size (at most 1000
/// lines of small JSON records) that the cost never matters in practice.
pub fn append_entries(path: &Path, entries: &[HistoryEntry]) -> std::io::Result<()> {
    if entries.is_empty() {
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let existing = match std::fs::read_to_string(path) {
        Ok(raw) => raw,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e),
    };

    let mut lines: Vec<String> =
        existing.lines().filter(|l| !l.trim().is_empty()).map(|l| l.to_string()).collect();

    for entry in entries {
        // `serde_json::to_string` on a plain data struct with no exotic
        // (non-UTF8-map-key, NaN float, ...) content cannot actually fail --
        // skip a hypothetical failure rather than aborting the whole append
        // over one bad entry.
        if let Ok(line) = serde_json::to_string(entry) {
            lines.push(line);
        }
    }

    if lines.len() > MAX_HISTORY_LINES {
        let excess = lines.len() - MAX_HISTORY_LINES;
        lines.drain(0..excess);
    }

    let mut content = lines.join("\n");
    content.push('\n');
    std::fs::write(path, content)
}

/// Formats `SystemTime::now()` as a UTC RFC3339 timestamp with 1-second
/// resolution, e.g. `"2024-01-15T10:30:00Z"`. See the module doc comment for
/// why this is hand-rolled instead of pulling in a time crate.
pub fn now_rfc3339() -> String {
    format_rfc3339(SystemTime::now())
}

fn format_rfc3339(t: SystemTime) -> String {
    let secs = t.duration_since(UNIX_EPOCH).unwrap_or_default().as_secs();
    let days = (secs / 86400) as i64;
    let time_of_day = secs % 86400;
    let (hour, minute, second) = (time_of_day / 3600, (time_of_day % 3600) / 60, time_of_day % 60);
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

/// Converts a day count since the Unix epoch (1970-01-01) into a
/// (year, month, day) civil calendar date, proleptic Gregorian, valid for
/// every day this app will ever run against. This is Howard Hinnant's
/// well-known `civil_from_days` algorithm
/// (<http://howardhinnant.github.io/date_algorithms.html>), transcribed
/// directly rather than reimplemented from scratch -- calendar math is easy
/// to get subtly wrong (leap years, month lengths) and this version is
/// widely used/verified prior art.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

/// Owns the background polling loop. No per-instance state -- the loop's
/// state (the previous snapshot) lives entirely inside the spawned task, so
/// this is just a namespace for the two `spawn*` constructors.
pub struct HistoryRecorder;

impl HistoryRecorder {
    /// Spawns the polling loop at `DEFAULT_POLL_INTERVAL` -- what
    /// `CoreManager::start` actually calls in production.
    pub fn spawn(clash_api_port: u16, history_path: PathBuf) -> JoinHandle<()> {
        Self::spawn_with_interval(clash_api_port, history_path, DEFAULT_POLL_INTERVAL)
    }

    /// Spawns the polling loop with an explicit `poll_interval` -- pulled out
    /// of `spawn` so tests can use a short interval instead of the real
    /// 5-second production cadence. Runs until the returned `JoinHandle` is
    /// `.abort()`-ed (see `CoreManager::stop_running`'s doc comment for why
    /// a hard abort, rather than a cooperative cancellation channel, is an
    /// acceptable choice for this particular loop) or the process exits.
    ///
    /// The first iteration only ever primes `previous` -- there is nothing
    /// to diff against yet on the very first poll after (re)starting, so no
    /// history can be produced from it. This deliberately means a connection
    /// that both starts *and* finishes inside one poll interval is invisible
    /// to history (never observed "present" in any snapshot) -- an accepted
    /// MVP gap given this is a best-effort look-back log, not a complete
    /// audit trail.
    ///
    /// Fetch/parse errors (Clash API unreachable mid-poll, e.g. a race with
    /// the proxy stopping) and write errors (disk full, permissions) are
    /// logged and skipped rather than ending the loop -- a transient failure
    /// to record one poll's worth of history shouldn't stop trying on the
    /// next tick.
    pub fn spawn_with_interval(
        clash_api_port: u16,
        history_path: PathBuf,
        poll_interval: Duration,
    ) -> JoinHandle<()> {
        tokio::spawn(async move {
            let mut previous: Option<ConnectionsSnapshot> = None;

            loop {
                tokio::time::sleep(poll_interval).await;

                let current = match crate::clash_api::get_connections(clash_api_port).await {
                    Ok(snapshot) => snapshot,
                    Err(e) => {
                        tracing::warn!("history recorder: failed to fetch connections: {e}");
                        continue;
                    }
                };

                if let Some(prev) = &previous {
                    let finished = diff_finished(prev, &current, &now_rfc3339());
                    if !finished.is_empty() {
                        if let Err(e) = append_entries(&history_path, &finished) {
                            tracing::warn!("history recorder: failed to write history: {e}");
                        }
                    }
                }

                previous = Some(current);
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use shared_types::ConnectionMetadata;
    use std::path::PathBuf;

    fn conn(id: &str) -> shared_types::ConnectionInfo {
        shared_types::ConnectionInfo {
            id: id.to_string(),
            metadata: ConnectionMetadata {
                network: "tcp".into(),
                host: "example.com".into(),
                destination_ip: "1.2.3.4".into(),
                destination_port: "443".into(),
            },
            upload: 10,
            download: 20,
            start: "2024-01-15T10:30:00Z".into(),
            chains: vec!["proxy".into()],
            rule: "".into(),
        }
    }

    fn snapshot(ids: &[&str]) -> ConnectionsSnapshot {
        ConnectionsSnapshot {
            download_total: 0,
            upload_total: 0,
            connections: ids.iter().map(|id| conn(id)).collect(),
        }
    }

    #[test]
    fn format_rfc3339_known_epoch_values() {
        assert_eq!(format_rfc3339(UNIX_EPOCH), "1970-01-01T00:00:00Z");
        // Widely-cited reference point: 1700000000 unix seconds is
        // 2023-11-14T22:13:20Z.
        assert_eq!(
            format_rfc3339(UNIX_EPOCH + Duration::from_secs(1_700_000_000)),
            "2023-11-14T22:13:20Z"
        );
    }

    #[test]
    fn diff_finished_returns_connections_no_longer_present() {
        let previous = snapshot(&["a", "b", "c"]);
        let current = snapshot(&["b"]); // "a" and "c" finished

        let finished = diff_finished(&previous, &current, "2024-01-15T10:31:00Z");

        let mut ids: Vec<&str> = finished.iter().map(|e| e.id.as_str()).collect();
        ids.sort();
        assert_eq!(ids, vec!["a", "c"]);
        assert!(finished.iter().all(|e| e.end == "2024-01-15T10:31:00Z"));
        // Everything else carries over from the live entry unchanged.
        let a = finished.iter().find(|e| e.id == "a").unwrap();
        assert_eq!(a.upload, 10);
        assert_eq!(a.download, 20);
        assert_eq!(a.start, "2024-01-15T10:30:00Z");
        assert_eq!(a.chains, vec!["proxy".to_string()]);
    }

    #[test]
    fn diff_finished_ignores_connections_still_present() {
        let previous = snapshot(&["a", "b"]);
        let current = snapshot(&["a", "b"]);

        let finished = diff_finished(&previous, &current, "now");
        assert!(finished.is_empty());
    }

    #[test]
    fn diff_finished_ignores_newly_appeared_connections() {
        let previous = snapshot(&["a"]);
        let current = snapshot(&["a", "b"]); // "b" is new, not finished

        let finished = diff_finished(&previous, &current, "now");
        assert!(finished.is_empty());
    }

    #[test]
    fn diff_finished_with_empty_previous_is_empty() {
        let previous = snapshot(&[]);
        let current = snapshot(&["a"]);
        assert!(diff_finished(&previous, &current, "now").is_empty());
    }

    fn temp_history_path(name: &str) -> PathBuf {
        let mut path = std::env::temp_dir();
        path.push(format!("ferroflow-history-test-{}-{}-{name}.jsonl", std::process::id(), unique_suffix()));
        path
    }

    fn unique_suffix() -> u128 {
        SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos()
    }

    #[test]
    fn append_entries_writes_json_lines_and_creates_file() {
        let path = temp_history_path("basic");
        let _ = std::fs::remove_file(&path);

        let entries = diff_finished(&snapshot(&["a", "b"]), &snapshot(&[]), "2024-01-15T10:31:00Z");
        append_entries(&path, &entries).expect("append should succeed");

        let raw = std::fs::read_to_string(&path).expect("file should exist");
        let lines: Vec<&str> = raw.lines().collect();
        assert_eq!(lines.len(), 2);
        for line in &lines {
            let parsed: HistoryEntry = serde_json::from_str(line).expect("valid json line");
            assert_eq!(parsed.end, "2024-01-15T10:31:00Z");
        }

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn append_entries_is_noop_for_empty_slice() {
        let path = temp_history_path("empty");
        let _ = std::fs::remove_file(&path);

        append_entries(&path, &[]).expect("no-op append should succeed");
        assert!(!path.exists(), "no file should be created for an empty diff");
    }

    #[test]
    fn append_entries_accumulates_across_calls() {
        let path = temp_history_path("accumulate");
        let _ = std::fs::remove_file(&path);

        let first = diff_finished(&snapshot(&["a"]), &snapshot(&[]), "t1");
        let second = diff_finished(&snapshot(&["b"]), &snapshot(&[]), "t2");
        append_entries(&path, &first).unwrap();
        append_entries(&path, &second).unwrap();

        let raw = std::fs::read_to_string(&path).unwrap();
        let ids: Vec<HistoryEntry> =
            raw.lines().map(|l| serde_json::from_str(l).unwrap()).collect();
        assert_eq!(ids.len(), 2);
        assert_eq!(ids[0].id, "a");
        assert_eq!(ids[1].id, "b");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn append_entries_caps_at_max_history_lines() {
        let path = temp_history_path("cap");
        let _ = std::fs::remove_file(&path);

        // Seed the file with exactly MAX_HISTORY_LINES pre-existing lines.
        let seeded: Vec<String> = (0..MAX_HISTORY_LINES)
            .map(|i| {
                serde_json::to_string(&HistoryEntry {
                    id: format!("seed-{i}"),
                    metadata: ConnectionMetadata {
                        network: "tcp".into(),
                        host: "".into(),
                        destination_ip: "".into(),
                        destination_port: "".into(),
                    },
                    upload: 0,
                    download: 0,
                    start: "t".into(),
                    end: "t".into(),
                    chains: vec![],
                    rule: "".into(),
                })
                .unwrap()
            })
            .collect();
        std::fs::write(&path, format!("{}\n", seeded.join("\n"))).unwrap();

        let new_entry = diff_finished(&snapshot(&["new-conn"]), &snapshot(&[]), "t-new");
        append_entries(&path, &new_entry).unwrap();

        let raw = std::fs::read_to_string(&path).unwrap();
        let lines: Vec<&str> = raw.lines().collect();
        assert_eq!(lines.len(), MAX_HISTORY_LINES, "file must be capped at MAX_HISTORY_LINES");

        // The oldest seeded line ("seed-0") must have been dropped, and the
        // newest entry must be present at the end.
        assert!(!raw.contains("\"seed-0\""));
        assert!(raw.contains("\"seed-1\""), "second-oldest line should survive the truncation");
        let last: HistoryEntry = serde_json::from_str(lines.last().unwrap()).unwrap();
        assert_eq!(last.id, "new-conn");

        let _ = std::fs::remove_file(&path);
    }

    /// Real end-to-end check, exercising the *actual* production wiring in
    /// `CoreManager::start`/`stop_running` (not `HistoryRecorder` called
    /// directly): sets a history path, starts a real sing-box instance with
    /// `connection_history_enabled: true`, drives a real client connection
    /// through its local `mixed` inbound out to a local fake "server" (a
    /// plain `TcpListener` standing in for the trojan server -- see inline
    /// comment for why that's more deterministic than a real remote host),
    /// confirms it's live via `list_connections()`, force-closes it, and
    /// confirms a real `HistoryEntry` ends up on disk once the recorder's
    /// spawned-by-`CoreManager` background task notices it's gone.
    ///
    /// This uses `HistoryRecorder::DEFAULT_POLL_INTERVAL` (the real 5-second
    /// production cadence) rather than a shortened one, specifically because
    /// `CoreManager` itself decides the interval (`history.rs`'s `spawn`,
    /// called internally, not exposed as a parameter) -- there is no way to
    /// exercise the real `start()`/`stop_running()` wiring with a faster
    /// interval without adding test-only surface to `CoreManager` for it.
    /// The pure diff/append logic is already covered fast and deterministically
    /// by the unit tests above; this test's unique value is confirming the
    /// two are actually wired together correctly end to end, so a slower
    /// real-timing run (roughly 15s) is an acceptable tradeoff. Not run by
    /// default (`#[ignore]`), needs a real binary at
    /// `<workspace root>/.dev-bin/sing-box[.exe]`, same convention as every
    /// other `real_singbox_*` test in this crate. Run manually with:
    /// `cargo test -p core-manager --all-targets -- --ignored real_singbox`
    #[tokio::test]
    #[ignore = "needs a real sing-box binary at <workspace root>/.dev-bin/"]
    async fn real_singbox_history_recorder_appends_entry_after_connection_closes() {
        use std::io::Write;
        use std::net::TcpStream;

        use crate::CoreManager;
        use shared_types::{Protocol, ProxyModeType, ServerConfig};

        let binary_name = if cfg!(windows) { "sing-box.exe" } else { "sing-box" };
        let binary =
            PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../../.dev-bin")).join(binary_name);
        assert!(binary.is_file(), "expected a real sing-box binary at {}", binary.display());

        // A plain local listener stands in for the trojan "server". It never
        // speaks the trojan protocol back -- it just accepts the TCP
        // connection and holds it open -- which is enough for sing-box's
        // trojan outbound to consider the underlying connection established
        // (trojan has no request/response handshake of its own; it just
        // writes a header onto an already-connected stream) and keep it
        // alive indefinitely. That gives this test a connection that stays
        // "active" in the Clash API until *we* deliberately close it via
        // `close_all_connections`, rather than racing against real network
        // timing to a real remote host (which would either resolve
        // instantly, making the presence window too short to reliably
        // observe, or hang unpredictably).
        let fake_server = std::net::TcpListener::bind("127.0.0.1:0").expect("bind fake server");
        let fake_server_port = fake_server.local_addr().unwrap().port();
        std::thread::spawn(move || {
            // Accept and hold every connection open for the test's duration
            // (leaked on purpose -- this thread/listener just lives until
            // the test process exits).
            let mut held = Vec::new();
            for stream in fake_server.incoming().flatten() {
                held.push(stream);
            }
        });

        let history_path = temp_history_path("real-singbox-e2e");
        let _ = std::fs::remove_file(&history_path);

        let manager = CoreManager::with_binary_path(binary);
        manager.set_history_path(Some(history_path.clone()));

        let server = ServerConfig {
            id: "s1".into(),
            name: "test".into(),
            protocol: Protocol::Trojan,
            address: "127.0.0.1".into(),
            port: fake_server_port,
            uuid: None,
            password: Some("pw".into()),
            encryption: None,
            flow: None,
            tls: None,
            wireguard_private_key: None,
            wireguard_peer_public_key: None,
            wireguard_pre_shared_key: None,
            wireguard_local_address: None,
        };

        let started = manager
            .start(&server, ProxyModeType::SystemProxy, &[], &std::collections::HashMap::new(), true)
            .await
            .expect("start should succeed against a real sing-box binary");
        let local_port = started.local_port.expect("SystemProxy run has a local mixed-inbound port");

        tokio::time::sleep(Duration::from_millis(300)).await;

        // Drive a real client connection through the local mixed inbound: a
        // plain HTTP CONNECT request, same as any HTTP proxy client. The
        // requested target (`1.2.3.4:80`) is irrelevant to where the traffic
        // actually goes -- `route.final` sends everything through the proxy
        // outbound regardless, which is our fake TCP server above.
        let mut client =
            TcpStream::connect(("127.0.0.1", local_port)).expect("connect to mixed inbound");
        client
            .write_all(b"CONNECT 1.2.3.4:80 HTTP/1.1\r\nHost: 1.2.3.4:80\r\n\r\n")
            .expect("write CONNECT request");

        // Poll our own `list_connections()` until the new connection shows
        // up (bounded wait, not a fixed sleep -- avoids flaking under slow
        // CI while still failing fast if it never appears).
        let mut connection_id = None;
        for _ in 0..50 {
            if let Ok(snapshot) = manager.list_connections().await {
                if let Some(c) = snapshot.connections.first() {
                    connection_id = Some(c.id.clone());
                    break;
                }
            }
            tokio::time::sleep(Duration::from_millis(100)).await;
        }
        let connection_id = connection_id.expect("connection should appear in the live snapshot");

        // The connection must survive past the recorder's *first* tick
        // (which only primes its `previous` snapshot -- see
        // `spawn_with_interval`'s doc comment) before we close it, otherwise
        // it would never have been observed as "present" at all and could
        // never be recorded as finished. Sleep past `DEFAULT_POLL_INTERVAL`
        // with a comfortable buffer, then close it.
        tokio::time::sleep(DEFAULT_POLL_INTERVAL + Duration::from_secs(1)).await;
        manager.close_all_connections().await.expect("close all connections");

        let mut gone = false;
        for _ in 0..50 {
            if let Ok(snapshot) = manager.list_connections().await {
                if !snapshot.connections.iter().any(|c| c.id == connection_id) {
                    gone = true;
                    break;
                }
            }
            tokio::time::sleep(Duration::from_millis(100)).await;
        }
        assert!(gone, "connection should disappear from the live snapshot after close_all_connections");

        // Now wait for the recorder's *next* tick (another
        // `DEFAULT_POLL_INTERVAL`) to notice the connection is gone and
        // write it to `history_path`, polling the file rather than sleeping
        // the full interval blindly.
        let mut recorded = None;
        let deadline = std::time::Instant::now() + DEFAULT_POLL_INTERVAL + Duration::from_secs(5);
        while std::time::Instant::now() < deadline {
            if let Ok(raw) = std::fs::read_to_string(&history_path) {
                if let Some(entry) = raw
                    .lines()
                    .filter_map(|l| serde_json::from_str::<HistoryEntry>(l).ok())
                    .find(|e| e.id == connection_id)
                {
                    recorded = Some(entry);
                    break;
                }
            }
            tokio::time::sleep(Duration::from_millis(200)).await;
        }

        let entry = recorded.expect("a HistoryEntry for the closed connection should be written");
        assert!(!entry.end.is_empty());
        assert_eq!(entry.id, connection_id);

        manager.stop().await.expect("stop should succeed");
        let _ = std::fs::remove_file(&history_path);
    }
}
