//! Windows privileged helper: runs as a LocalSystem Windows Service
//! (`windows-service` crate), listens on a named pipe
//! (`helper_proto::endpoints::WINDOWS_PIPE`) with an ACL restricting
//! connections to SYSTEM + the interactive user (defense in depth on top
//! of the shared-token auth, same model as macOS).
//!
//! Reference for behavior (not wire format): `helper-win/` (Go) in the
//! Electron repo -- service.go/winproc.go/selfuninstall.go.
//!
//! Flags:
//!   --console    Run in the foreground without the SCM, for dev/test
//!                (matches the Go helper's dev workflow). No admin rights
//!                needed beyond whatever `--install` already set up.
//!   --install    One-time, admin-required setup: generate + ACL the
//!                shared token, register this exe as a LocalSystem
//!                service, and start it. See `install.rs`.
//!   --uninstall  Reverse of --install: stop + delete the service, remove
//!                the token and managed core dir. Also admin-required.
//!   (none)       Default: run as the registered service (this is what
//!                the SCM invokes on boot/start).
//!
//! No-ops on non-Windows hosts so `cargo check --workspace` passes from
//! macOS/Linux dev machines.

#[cfg(windows)]
mod install;
#[cfg(windows)]
mod pipe_acl;
#[cfg(windows)]
mod service;
#[cfg(windows)]
mod winproc;

fn main() {
    tracing_subscriber::fmt::init();

    #[cfg(windows)]
    {
        let args: Vec<String> = std::env::args().collect();
        let has = |flag: &str| args.iter().any(|a| a == flag);
        let value_of = |flag: &str| -> Option<String> {
            args.iter().position(|a| a == flag).and_then(|i| args.get(i + 1)).cloned()
        };

        let result: anyhow::Result<()> = if has("--console") {
            let rt = tokio::runtime::Runtime::new().expect("tokio runtime");
            rt.block_on(service::run_console())
        } else if has("--install") {
            // `--token-file <path>`: the token is generated by the
            // unprivileged caller (src-tauri), not here -- see
            // `install::install`'s doc comment for why (the ACL'd
            // destination file is SYSTEM+Administrators-only, so a
            // standard-user app process could never read a
            // helper-generated token back afterwards; the app must
            // already hold the value it wants persisted).
            match value_of("--token-file") {
                Some(path) => install::install(std::path::Path::new(&path)),
                None => Err(anyhow::anyhow!("--install requires --token-file <path>")),
            }
        } else if has("--uninstall") {
            install::uninstall()
        } else {
            service::run_as_service()
        };

        if let Err(err) = result {
            tracing::error!("helper-windows exited: {err:#}");
            // `--install`/`--uninstall` run elevated via `ShellExecuteExW`
            // from src-tauri's `run_elevated` (see that function's doc
            // comment), which does not redirect the child's stdout/stderr
            // anywhere the caller can read -- without this, every failure
            // here collapsed into an opaque "installer exited with code 1"
            // on the UI side, with the real reason (a `create_service`
            // failure, an `icacls` failure, a missing token file, etc.)
            // visible only in a console window nobody's watching during an
            // elevation prompt. Best-effort: written next to the running
            // exe (always writable/discoverable regardless of which
            // account UAC elevation actually ran as, unlike a path under
            // the *unprivileged* caller's `%TEMP%`), so
            // `helper_windows.rs`'s `install`/`uninstall` commands can read
            // it back and fold the real message into the error they
            // surface to the frontend.
            if let Ok(exe) = std::env::current_exe() {
                if let Some(dir) = exe.parent() {
                    let _ = std::fs::write(
                        dir.join(helper_proto::endpoints::WINDOWS_INSTALL_ERROR_LOG_NAME),
                        format!("{err:#}"),
                    );
                }
            }
            std::process::exit(1);
        }
    }

    #[cfg(not(windows))]
    {
        eprintln!("helper-windows only runs on Windows");
        std::process::exit(1);
    }
}
